---
# tasks file for wireguard
- name: system configuration
  tags: system
  block:
    - name: install wireguard tools
      ansible.builtin.dnf:
        name: wireguard-tools
        state: latest
      notify:
        - reload_systemd

- name: wireguard configuration
  block:
    - name: Create WireGuard configurations directory
      file:
        dest: /etc/wireguard
        state: directory

    - name: Generate WireGuard configuration file
      template:
        src: wireguard.conf.j2
        dest: "/etc/wireguard/{{ wireguard_iface }}.conf"
        owner: root
        group: root
        mode: 0600
      notify:
        - reload_service

- name: network configuration
  block:
    - name: Enable packet forwarding for IPv4
      sysctl:
        name: net.ipv4.ip_forward
        value: 1
        sysctl_set: yes
        state: present
        reload: yes

    - name: Add WireGuard as a service to FirewallD
      template:
        src: firewalld.xml.j2
        dest: /etc/firewalld/services/wireguard.xml
        owner: root
        group: root
        mode: 0600
      register: firewalld_service

    - name: Reload firewalld to add/update wireguard service
      ansible.builtin.command: "firewall-cmd --reload"
      when: firewalld_service.changed

    - name: Allow WireGuard service for FirewallD public zone
      firewalld:
        zone: public
        service: wireguard
        state: enabled
        permanent: yes
        immediate: yes

    - name: Add WireGuard interface to FirewallD public zone
      firewalld:
        zone: internal
        interface: wg0
        state: enabled
        permanent: yes
        immediate: yes

    - name: Enable Masquerading
      firewalld:
        zone: public
        masquerade: yes
        state: enabled
        permanent: yes
        immediate: yes
    - name: Enable Masquerading for internal zone
      firewalld:
        zone: internal
        masquerade: yes
        state: enabled
        permanent: yes
        immediate: yes

    - name: Enable and start wireguard
      ansible.builtin.service:
        name: "wg-quick@{{ wireguard_iface }}"
        state: started
        enabled: yes
