---
# tasks file for wireguard
- name: system configuration
  tags: system
  block:
    - name: install wireguard tools
      ansible.builtin.dnf:
        name: wireguard-tools
        state: latest
      notify:
        - reload_systemd

- name: network connection
  block:
    - name: network manager configuration
      template:
        src: wireguard.conf.j2
        dest: "{{ wireguard_nm_connections_folder }}/{{ wireguard_iface }}.nmconnection"
        owner: root
        group: root
        mode: 0600
        force: yes
      register: nmconnection

    - name: reload interface
      ansible.builtin.command: "nmcli c reload"
      when: nmconnection.changed

- name: netfiler and ip forwarding configuration
  block:
    - name: Enable packet forwarding for IPv4
      sysctl:
        name: net.ipv4.ip_forward
        value: 1
        sysctl_set: yes
        state: present
        reload: yes

    - name: Add WireGuard as a service to FirewallD
      template:
        src: firewalld.xml.j2
        dest: /etc/firewalld/services/wireguard.xml
        owner: root
        group: root
        mode: 0600
      register: firewalld_service

    - name: Reload firewalld to add/update wireguard service
      ansible.builtin.command: "firewall-cmd --reload"
      when: firewalld_service.changed

    - name: Allow WireGuard service for FirewallD public zone
      firewalld:
        zone: public
        service: wireguard
        state: enabled
        permanent: yes
        immediate: yes

    - name: Add WireGuard interface to FirewallD public zone
      firewalld:
        zone: internal
        interface: wg0
        state: enabled
        permanent: yes
        immediate: yes

    - name: Enable Masquerading
      firewalld:
        zone: public
        masquerade: yes
        state: enabled
        permanent: yes
        immediate: yes
    - name: Enable Masquerading for internal zone
      firewalld:
        zone: internal
        masquerade: yes
        state: enabled
        permanent: yes
        immediate: yes
