---
# tasks file for wireguard
- name: system configuration
  - name: install wireguard tools
    ansible.builtin.dnf:
      name: wireguard-tools
      state: latest

- name: wireguard configuration
  block:
    - name: Create WireGuard configurations directory
      file:
	dest: /etc/wireguard
	state: directory

    - name: Generate WireGuard private and public keys
      shell: umask 077 && wg genkey | tee /etc/wireguard/privatekey | wg pubkey > /etc/wireguard/publickey

- name: network configuration
  block:
    - name: Enable packet forwarding for IPv4
      sysctl:
        name: net.ipv4.ip_forward
        value: 1
        sysctl_set: yes
        state: present
        reload: yes

    - name: Add WireGuard as a service to FirewallD
      template:
	src: wireguard.xml.j2
	dest: /etc/firewalld/services/wireguard.xml
	owner: root
	group: root
	mode: 0600
	force: no

    - name: Allow WireGuard service for FirewallD public zone
      firewalld:
	zone: public
	service: wireguard
	state: enabled
	permanent: yes
	immediate: yes

    - name: Add WireGuard interface to FirewallD public zone
      firewalld:
	zone: public
	interface: wg0
	state: enabled
	permanent: yes
	immediate: yes

    - name: Enable Masquerading
      firewalld:
	zone: public
	masquerade: yes
	state: enabled
	permanent: yes
	immediate: yes

